2024-01-19 03:43:52,791 : INFO : Start of Training
2024-01-19 03:43:52,794 : INFO : Run_id: 2024-01-19_034352_962438271
2024-01-19 03:43:52,796 : INFO : Start of Data Load, validation and transformation...
2024-01-19 03:43:52,796 : INFO : Start of Archiving Old Rejected Files...
2024-01-19 03:43:52,797 : INFO : End of Archiving Old Rejected Files...
2024-01-19 03:43:52,797 : INFO : Start of Archiving Old Validated Files...
2024-01-19 03:43:52,797 : INFO : End of Archiving Old Validated Files...
2024-01-19 03:43:52,797 : INFO : Start of Archiving Old Processed Files...
2024-01-19 03:43:52,797 : INFO : End of Archiving Old Processed Files...
2024-01-19 03:43:52,797 : INFO : Start of Archiving Old Result Files...
2024-01-19 03:43:52,797 : INFO : End of Archiving Old Result Files...
2024-01-19 03:43:52,797 : INFO : Start of Reading values From Schema...
2024-01-19 03:43:52,797 : INFO : End of Reading values From Schema...
2024-01-19 03:43:52,797 : INFO : Start of Validating Column Length...
2024-01-19 03:43:52,797 : INFO : End of Validating column Length
2024-01-19 03:43:52,797 : INFO : Start of Validating Missing Values...
2024-01-19 03:43:52,797 : INFO : End of Validating Missing Values
2024-01-19 03:43:52,797 : INFO : Start of Replacing Missing Values with NULL...
2024-01-19 03:43:52,797 : INFO : End of Replacing Missing Values with NULL...
2024-01-19 03:43:52,797 : INFO : Start of Creating Table...
2024-01-19 03:43:52,797 : INFO : Opened training database successfully
2024-01-19 03:43:52,797 : INFO : Tables created successfully
2024-01-19 03:43:52,797 : INFO : Closed training database successfully
2024-01-19 03:43:52,797 : INFO : End of Creating Table...
2024-01-19 03:43:52,797 : INFO : Opened training database successfully
2024-01-19 03:43:52,798 : INFO : Start of Inserting Data into Table...
2024-01-19 03:43:52,798 : INFO : End of Inserting Data into Table...
2024-01-19 03:43:52,798 : INFO : Start of Exporting Data into CSV...
2024-01-19 03:43:52,798 : INFO : Opened training database successfully
2024-01-19 03:43:52,881 : INFO : End of Exporting Data into CSV...
2024-01-19 03:43:52,886 : INFO : Start of Moving Processed Files...
2024-01-19 03:43:52,886 : INFO : End of Moving Processed Files...
2024-01-19 03:43:52,886 : INFO : End of Data Load, validation and transformation
2024-01-19 03:43:52,886 : INFO : Start of Preprocessing...
2024-01-19 03:43:52,886 : INFO : Start of Reading dataset...
2024-01-19 03:43:52,923 : INFO : End of reading dataset...
2024-01-19 03:43:52,924 : INFO : Start of Droping columns...
2024-01-19 03:43:52,924 : INFO : End of Droping columns...
2024-01-19 03:43:52,924 : INFO : Start of feature encoding...
2024-01-19 03:43:52,926 : INFO : End of feature encoding...
2024-01-19 03:43:52,928 : INFO : Start of Droping columns...
2024-01-19 03:43:52,928 : INFO : End of Droping columns...
2024-01-19 03:43:52,931 : INFO : Start of finding missing values...
2024-01-19 03:43:52,934 : INFO : Start of finding missing values...
2024-01-19 03:43:52,937 : INFO : Start of Imputing missing values...
2024-01-19 03:43:52,963 : INFO : End of Imputing missing values...
2024-01-19 03:43:52,964 : INFO : Start of splitting features and label...
2024-01-19 03:43:52,965 : INFO : End of splitting features and label...
2024-01-19 03:43:52,965 : INFO : End of Preprocessing...
2024-01-19 03:43:52,965 : INFO : Start of elbow plotting...
2024-01-19 03:44:09,801 : INFO : The optimum number of clusters is: 3
2024-01-19 03:44:09,801 : INFO : End of elbow plotting...
2024-01-19 03:44:09,801 : ERROR : Unsuccessful End of Training
Traceback (most recent call last):
  File "/home/draeghonvm/Projects/Supervised_ML_Project/env/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3791, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Cluster'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/draeghonvm/Projects/Supervised_ML_Project/apps/training/train_model.py", line 69, in training_model
    self.X['Labels'] = self.y
                       ^^^^^^^
  File "/home/draeghonvm/Projects/Supervised_ML_Project/env/lib/python3.11/site-packages/pandas/core/frame.py", line 3893, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/draeghonvm/Projects/Supervised_ML_Project/env/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3798, in get_loc
    raise KeyError(key) from err
KeyError: 'Cluster'
